#Requires -Version 5.1
<#
.SYNOPSIS
    Defender Live Response wrapper for the Cyber Triage Collector.

.DESCRIPTION
    Thin wrapper invoked by MDE Live Response. Launches a detached local worker
    that runs CyberTriageCollector.exe against the local machine, writes encrypted
    output to disk, uploads the encrypted output to the tenant's Azure Blob
    container using a short-lived SAS URL supplied by the Logic App at runtime,
    and leaves the encrypted local output in place. The Live Response session
    does NOT wait for collection to complete (avoids MDE LR's 60-min cap).

    Library files required (both uploaded to the MDE Live Response Library):
      - CyberTriageCollector.exe   (customer-supplied collector binary)
      - Run-CyberTriage.ps1        (this wrapper)

    Live Response sequence executed by the Logic App:
            1. PutFile  CyberTriageCollector.exe
            2. RunScript Run-CyberTriage.ps1 -AzureSasUrl <runtime SAS>
           (returns within ~1 minute)

        The worker continues running on the host, uploads the encrypted artifact to
        blob storage when the scan completes, and keeps a local encrypted copy under
        C:\CyberTriage\keep.

.PARAMETER AzureSasUrl
    Short-lived Azure Blob container SAS URL generated by the Logic App. This
    value is intentionally not written to status/log files.

.PARAMETER Profile
    Optional. fast adds --fast for testing; full is the production default.

.NOTES
    Standard collection password: "infected" (customer-specified).
    Analysts open cttout_*.json.gz.enc or cttout_*.json.gz.enc.* in the Cyber Triage product with this password.

    Exit codes:
            0   success - worker launched
      2   collector binary not found next to script
            3   failed to launch worker
            4   invalid or missing AzureSasUrl
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$AzureSasUrl,

    [ValidateSet('fast', 'full')]
    [string]$Profile = 'full'
)

$ErrorActionPreference = 'Stop'

# === Tenant configuration (edit per environment) ============================
$Pw = 'infected'
# ============================================================================

$scriptDir       = Split-Path -Parent $MyInvocation.MyCommand.Path
$collector       = Join-Path $scriptDir 'CyberTriageCollector.exe'
$runtimeRoot     = 'C:\CyberTriage'
$binDir          = Join-Path $runtimeRoot 'bin'
$workDir         = Join-Path $runtimeRoot 'work'
$keepDir         = Join-Path $runtimeRoot 'keep'
$cleanupDays     = 7
$runStamp        = (Get-Date).ToUniversalTime().ToString('yyyyMMdd_HHmmss')
$stagedCollector = Join-Path $binDir "CyberTriageCollector_$runStamp.exe"
$logFile         = Join-Path $workDir "cttout_$runStamp.log"
$workerLogFile   = Join-Path $workDir "ctworker_$runStamp.log"
$workerScript    = Join-Path $workDir "Run-CyberTriageWorker_$runStamp.ps1"
$statusPath      = Join-Path $workDir 'cttout.status.json'

function Write-Status {
    param([string]$State, [int]$ExitCode, [string]$Detail = '')
    if (-not (Test-Path $workDir)) { New-Item -ItemType Directory -Path $workDir -Force | Out-Null }
    @{
        host           = $env:COMPUTERNAME
        timestampUtc   = (Get-Date).ToUniversalTime().ToString('o')
        state          = $State
        exitCode       = $ExitCode
        detail         = $Detail
        profile        = $Profile
        authMode       = 'azure_sas_url'
        collector      = $collector
        stagedCollector = $stagedCollector
        workerScript   = $workerScript
        workerLogFile  = $workerLogFile
        logFile        = $logFile
        errorLogFile   = "$logFile.err"
        runtimeRoot    = $runtimeRoot
        keepDir        = $keepDir
    } | ConvertTo-Json -Depth 3 | Out-File -FilePath $statusPath -Encoding UTF8 -Force
}

if ($AzureSasUrl -notmatch '^https://[^?]+\.blob\.[^/]+/.+\?.+') {
    Write-Status -State 'error' -ExitCode 4 -Detail 'AzureSasUrl must be a full HTTPS Azure Blob SAS URL.'
    Write-Error 'AzureSasUrl must be a full HTTPS Azure Blob SAS URL.'
    exit 4
}

# 1. Pre-flight: collector present
if (-not (Test-Path -LiteralPath $collector)) {
    Write-Status -State 'error' -ExitCode 2 -Detail "Collector not found at $collector"
    Write-Error "CyberTriageCollector.exe not found alongside script ($scriptDir)."
    exit 2
}

# 2. Ensure runtime dirs exist and trim old staged/log files
foreach ($path in @($runtimeRoot, $binDir, $workDir, $keepDir)) {
    if (-not (Test-Path $path)) { New-Item -ItemType Directory -Path $path -Force | Out-Null }
}

$cleanupBefore = (Get-Date).AddDays(-$cleanupDays)
Get-ChildItem -LiteralPath $binDir -Filter 'CyberTriageCollector_*.exe' -File -ErrorAction SilentlyContinue |
    Where-Object { $_.LastWriteTime -lt $cleanupBefore } |
    Remove-Item -Force -ErrorAction SilentlyContinue
Get-ChildItem -LiteralPath $workDir -File -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -ne 'cttout.status.json' -and $_.LastWriteTime -lt $cleanupBefore } |
    Remove-Item -Force -ErrorAction SilentlyContinue

Copy-Item -LiteralPath $collector -Destination $stagedCollector -Force

# 3. Create a detached worker. The worker keeps the encrypted local output and
#    uploads that same file to the SAS container after collection completes.
$workerSource = @'
#Requires -Version 5.1
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)] [string]$AzureSasUrl,
    [Parameter(Mandatory = $true)] [ValidateSet('fast', 'full')] [string]$Profile,
    [Parameter(Mandatory = $true)] [string]$StagedCollector,
    [Parameter(Mandatory = $true)] [string]$WorkDir,
    [Parameter(Mandatory = $true)] [string]$KeepDir,
    [Parameter(Mandatory = $true)] [string]$Pw,
    [Parameter(Mandatory = $true)] [string]$RunStamp,
    [Parameter(Mandatory = $true)] [string]$LogFile,
    [Parameter(Mandatory = $true)] [string]$WorkerLogFile,
    [Parameter(Mandatory = $true)] [string]$StatusPath
)

$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

function Write-WorkerLog {
    param([string]$Message)
    $line = '{0} {1}' -f (Get-Date).ToUniversalTime().ToString('o'), $Message
    Add-Content -LiteralPath $WorkerLogFile -Value $line -Encoding UTF8
}

function Write-WorkerStatus {
    param([string]$State, [int]$ExitCode, [string]$Detail = '', [string[]]$UploadedFiles = @())
    @{
        host             = $env:COMPUTERNAME
        timestampUtc     = (Get-Date).ToUniversalTime().ToString('o')
        state            = $State
        exitCode         = $ExitCode
        detail           = $Detail
        profile          = $Profile
        authMode         = 'wrapper_managed_sas_upload'
        stagedCollector  = $StagedCollector
        logFile          = $LogFile
        errorLogFile     = "$LogFile.err"
        workerLogFile    = $WorkerLogFile
        keepDir          = $KeepDir
        uploadedFiles    = $UploadedFiles
    } | ConvertTo-Json -Depth 4 | Out-File -LiteralPath $StatusPath -Encoding UTF8 -Force
}

function Get-BlobUploadUrl {
    param(
        [Parameter(Mandatory = $true)] [string]$ContainerSasUrl,
        [Parameter(Mandatory = $true)] [string]$BlobName
    )

    $parts = $ContainerSasUrl -split '\?', 2
    if ($parts.Count -ne 2) { throw 'AzureSasUrl must include a SAS query string.' }

    $containerUrl = $parts[0].TrimEnd('/')
    $sasQuery = $parts[1]
    $encodedBlobName = [Uri]::EscapeDataString($BlobName)
    return "$containerUrl/$encodedBlobName`?$sasQuery"
}

function Send-FileToBlob {
    param(
        [Parameter(Mandatory = $true)] [string]$UploadUrl,
        [Parameter(Mandatory = $true)] [System.IO.FileInfo]$File
    )

    $request = [System.Net.HttpWebRequest]::Create($UploadUrl)
    $request.Method = 'PUT'
    $request.Headers.Add('x-ms-blob-type', 'BlockBlob')
    $request.Headers.Add('x-ms-version', '2020-12-06')
    $request.Headers.Add('x-ms-date', (Get-Date).ToUniversalTime().ToString('R'))
    $request.ContentLength = $File.Length
    $request.AllowWriteStreamBuffering = $false

    $fileStream = [System.IO.File]::OpenRead($File.FullName)
    try {
        $requestStream = $request.GetRequestStream()
        try { $fileStream.CopyTo($requestStream) }
        finally { $requestStream.Dispose() }
    }
    finally { $fileStream.Dispose() }

    $response = $request.GetResponse()
    try { return [int]$response.StatusCode }
    finally { $response.Dispose() }
}

try {
    foreach ($path in @($WorkDir, $KeepDir)) {
        if (-not (Test-Path -LiteralPath $path)) { New-Item -ItemType Directory -Path $path -Force | Out-Null }
    }

    $baseName = 'cttout_{0}_{1}' -f $env:COMPUTERNAME, $RunStamp
    $localOutput = Join-Path $KeepDir "$baseName.json"
    $collectorArgs = @(
        '-o', $localOutput,
        '--encrypt_outfile', $Pw, $Pw,
        '--tempdir', $WorkDir
    )
    if ($Profile -eq 'fast') { $collectorArgs += '--fast' }

    Write-WorkerStatus -State 'collecting' -ExitCode 0 -Detail "Collector starting; local output path $localOutput."
    Write-WorkerLog "Starting collector $StagedCollector with profile $Profile."

    $collectorProcess = Start-Process -FilePath $StagedCollector `
                                      -ArgumentList $collectorArgs `
                                      -WindowStyle Hidden `
                                      -PassThru `
                                      -Wait `
                                      -RedirectStandardOutput $LogFile `
                                      -RedirectStandardError "$LogFile.err"
    $collectorProcess.Refresh()
    $collectorExitCode = $collectorProcess.ExitCode
    if ($null -eq $collectorExitCode) {
        $collectorErrorLog = if (Test-Path -LiteralPath "$LogFile.err") { Get-Content -LiteralPath "$LogFile.err" -Raw -ErrorAction SilentlyContinue } else { '' }
        if ($collectorErrorLog -match 'Collection completed successfully') {
            $collectorExitCode = 0
            Write-WorkerLog 'Collector exit code was unavailable; success confirmed from collector log.'
        } else {
            Write-WorkerStatus -State 'error' -ExitCode 7 -Detail "Collector exit code unavailable. See $LogFile.err."
            exit 7
        }
    }
    Write-WorkerLog "Collector exited with code $collectorExitCode."

    if ($collectorExitCode -ne 0) {
        Write-WorkerStatus -State 'error' -ExitCode $collectorExitCode -Detail "Collector failed. See $LogFile.err."
        exit $collectorExitCode
    }

    $encryptedFiles = @(
        Get-ChildItem -LiteralPath $KeepDir -Filter "$baseName.json.gz.enc" -File -ErrorAction SilentlyContinue
        Get-ChildItem -LiteralPath $KeepDir -Filter "$baseName.json.gz.enc.*" -File -ErrorAction SilentlyContinue
    ) | Sort-Object FullName -Unique
    if (-not $encryptedFiles) {
        Write-WorkerStatus -State 'error' -ExitCode 5 -Detail "No encrypted output files found for $baseName in $KeepDir."
        exit 5
    }

    Write-WorkerStatus -State 'uploading' -ExitCode 0 -Detail "Uploading $($encryptedFiles.Count) encrypted file(s)." -UploadedFiles ($encryptedFiles.Name)
    foreach ($file in $encryptedFiles) {
        Write-WorkerLog "Uploading $($file.Name) ($($file.Length) bytes)."
        $uploadUrl = Get-BlobUploadUrl -ContainerSasUrl $AzureSasUrl -BlobName $file.Name
        $statusCode = Send-FileToBlob -UploadUrl $uploadUrl -File $file
        Write-WorkerLog "Uploaded $($file.Name) with HTTP $statusCode."
    }

    Write-WorkerStatus -State 'completed' -ExitCode 0 -Detail "Uploaded $($encryptedFiles.Count) encrypted file(s) and kept local copies in $KeepDir." -UploadedFiles ($encryptedFiles.Name)
    Write-WorkerLog 'Collection, upload, and local retention completed successfully.'
    exit 0
} catch {
    Write-WorkerLog "ERROR: $($_.Exception.Message)"
    Write-WorkerStatus -State 'error' -ExitCode 6 -Detail $_.Exception.Message
    exit 6
}
'@

$workerSource | Out-File -LiteralPath $workerScript -Encoding UTF8 -Force

# 4. Launch the worker as a detached background process so the LR session can
#    return immediately. The worker keeps running and uploads when complete.
try {
    $workerArgs = @(
        '-NoProfile',
        '-ExecutionPolicy', 'Bypass',
        '-File', $workerScript,
        '-AzureSasUrl', $AzureSasUrl,
        '-Profile', $Profile,
        '-StagedCollector', $stagedCollector,
        '-WorkDir', $workDir,
        '-KeepDir', $keepDir,
        '-Pw', $Pw,
        '-RunStamp', $runStamp,
        '-LogFile', $logFile,
        '-WorkerLogFile', $workerLogFile,
        '-StatusPath', $statusPath
    )
    $proc = Start-Process -FilePath 'powershell.exe' `
                          -ArgumentList $workerArgs `
                          -WindowStyle Hidden `
                          -PassThru
} catch {
    Write-Status -State 'error' -ExitCode 3 -Detail "Failed to launch worker: $($_.Exception.Message)"
    exit 3
}

Write-Status -State 'launched' -ExitCode 0 -Detail "Worker PID $($proc.Id); staged collector at $stagedCollector; local output will be retained in $keepDir and uploaded via runtime SAS URL."
Write-Output "OK worker PID $($proc.Id) running in background; encrypted artifact will be kept locally in $keepDir and uploaded via runtime SAS URL."
exit 0
