#Requires -Version 5.1
<#
.SYNOPSIS
    Defender Live Response wrapper for the Cyber Triage Collector.

.DESCRIPTION
    Thin wrapper invoked by MDE Live Response. Launches CyberTriageCollector.exe
    against the local machine. The collector encrypts the output and uploads it
    directly to the tenant's Azure Blob container using a short-lived SAS URL
    supplied by the Logic App at runtime. The Live Response session does NOT wait
    for collection to complete (avoids MDE LR's 60-min cap).

    Library files required (both uploaded to the MDE Live Response Library):
      - CyberTriageCollector.exe   (customer-supplied collector binary)
      - Run-CyberTriage.ps1        (this wrapper)

    Live Response sequence executed by the Logic App:
      1. PutFile  CyberTriageCollector.exe
        2. RunScript Run-CyberTriage.ps1 -AzureSasUrl <runtime SAS> -Profile <fast|full>
           (returns within ~1 minute)

    The collector continues running on the host and uploads the encrypted
    artifact directly to blob storage when the full forensic scan completes.

.PARAMETER AzureSasUrl
    Short-lived Azure Blob container SAS URL generated by the Logic App. This
    value is intentionally not written to status/log files.

.PARAMETER Profile
    fast    : --fast (skips full filesystem scan, ~5-10 min)
    full    : full collection (default; ~30 min on workstation, longer on server)

.NOTES
    Standard collection password: "infected" (customer-specified).
    Analysts open cttout_*.json.gz.enc.* in the Cyber Triage product with this password.

    Exit codes:
      0   success - collector launched
      2   collector binary not found next to script
      3   failed to launch collector
    4   invalid or missing AzureSasUrl
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$AzureSasUrl,

    [ValidateSet('fast', 'full')]
    [string]$Profile = 'full'
)

$ErrorActionPreference = 'Stop'

# === Tenant configuration (edit per environment) ============================
$Pw = 'infected'
# ============================================================================

$scriptDir       = Split-Path -Parent $MyInvocation.MyCommand.Path
$collector       = Join-Path $scriptDir 'CyberTriageCollector.exe'
$runtimeRoot     = 'C:\CyberTriage'
$binDir          = Join-Path $runtimeRoot 'bin'
$workDir         = Join-Path $runtimeRoot 'work'
$cleanupDays     = 7
$runStamp        = (Get-Date).ToUniversalTime().ToString('yyyyMMdd_HHmmss')
$stagedCollector = Join-Path $binDir "CyberTriageCollector_$runStamp.exe"
$logFile         = Join-Path $workDir "cttout_$runStamp.log"
$statusPath      = Join-Path $workDir 'cttout.status.json'

function Write-Status {
    param([string]$State, [int]$ExitCode, [string]$Detail = '')
    if (-not (Test-Path $workDir)) { New-Item -ItemType Directory -Path $workDir -Force | Out-Null }
    @{
        host           = $env:COMPUTERNAME
        timestampUtc   = (Get-Date).ToUniversalTime().ToString('o')
        state          = $State
        exitCode       = $ExitCode
        detail         = $Detail
        profile        = $Profile
        authMode       = 'azure_sas_url'
        collector      = $collector
        stagedCollector = $stagedCollector
        logFile        = $logFile
        errorLogFile   = "$logFile.err"
        runtimeRoot    = $runtimeRoot
    } | ConvertTo-Json -Depth 3 | Out-File -FilePath $statusPath -Encoding UTF8 -Force
}

if ($AzureSasUrl -notmatch '^https://[^?]+\.blob\.[^/]+/.+\?.+') {
    Write-Status -State 'error' -ExitCode 4 -Detail 'AzureSasUrl must be a full HTTPS Azure Blob SAS URL.'
    Write-Error 'AzureSasUrl must be a full HTTPS Azure Blob SAS URL.'
    exit 4
}

# 1. Pre-flight: collector present
if (-not (Test-Path -LiteralPath $collector)) {
    Write-Status -State 'error' -ExitCode 2 -Detail "Collector not found at $collector"
    Write-Error "CyberTriageCollector.exe not found alongside script ($scriptDir)."
    exit 2
}

# 2. Ensure runtime dirs exist and trim old staged/log files
foreach ($path in @($runtimeRoot, $binDir, $workDir)) {
    if (-not (Test-Path $path)) { New-Item -ItemType Directory -Path $path -Force | Out-Null }
}

$cleanupBefore = (Get-Date).AddDays(-$cleanupDays)
Get-ChildItem -LiteralPath $binDir -Filter 'CyberTriageCollector_*.exe' -File -ErrorAction SilentlyContinue |
    Where-Object { $_.LastWriteTime -lt $cleanupBefore } |
    Remove-Item -Force -ErrorAction SilentlyContinue
Get-ChildItem -LiteralPath $workDir -File -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -ne 'cttout.status.json' -and $_.LastWriteTime -lt $cleanupBefore } |
    Remove-Item -Force -ErrorAction SilentlyContinue

Copy-Item -LiteralPath $collector -Destination $stagedCollector -Force

# 3. Build args - collector uploads directly to Azure Blob via runtime SAS URL
$collectorArgs = @(
    '--encrypt_outfile', $Pw, $Pw,
    '--azure_SasUrl',    $AzureSasUrl,
    '--tempdir',         $workDir
)
if ($Profile -eq 'fast') { $collectorArgs += '--fast' }

# 4. Launch collector as a detached background process so the LR session can
#    return immediately. Collector keeps running and uploads when complete.
try {
    $proc = Start-Process -FilePath $stagedCollector `
                          -ArgumentList $collectorArgs `
                          -WindowStyle Hidden `
                          -PassThru `
                          -RedirectStandardOutput $logFile `
                          -RedirectStandardError  "$logFile.err"
} catch {
    Write-Status -State 'error' -ExitCode 3 -Detail "Failed to launch collector: $($_.Exception.Message)"
    exit 3
}

Write-Status -State 'launched' -ExitCode 0 -Detail "Collector PID $($proc.Id); staged at $stagedCollector; SAS upload started."
Write-Output "OK collector PID $($proc.Id) running in background; artifact will upload via runtime SAS URL."
exit 0
